[package]
name = "bashpack"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
regex = "1.11"

[dev-dependencies]
assert_cmd = "2.0.17"
assert_fs = "1.1.3"
